"""
Used to compare thermo data between high level calcs in a paper and those generated by group
additivity in RMG-Py
"""
from rmgpy.data.rmg import RMGDatabase
from rmgpy import settings
from rmgpy.molecule import Molecule
from rmgpy.species import Species
###################################
rmg_database = RMGDatabase()
rmg_database.load(settings['database.directory'], kineticsFamilies='none', reactionLibraries=[])

with open('/Users/belinda/Code/RMG-Py/SiH_rad_thermo_Katzer.txt', 'r') as thermo_data:
    rad_species = thermo_data.read().split('\n\n')
    for entry in rad_species:
        label = entry.split('\n')[0]
        adj_list = ""
        for line in entry.split('\n')[1:]:
            if 'u' in line: adj_list += line + '\n'
            else: break
       # print adj_list
        H298 = entry.split('\n')[-1]
        mol = Molecule().fromAdjacencyList(adj_list)
        thermoData = rmg_database.thermo.getThermoDataFromGroups(Species(molecule=mol.generateResonanceIsomers()))
        print label + '\t' + H298 + '\t' + str(thermoData.H298.value_si/1000) + '\t' + thermoData.comment
